# Generated by Django 2.2.2 on 2019-06-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='isbn',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='website',
            field=models.CharField(help_text='200 Character <a href="https://www.website-international.org/content/what-website">Website</a>', max_length=200, null=True, verbose_name='Website'),
        ),
    ]
