# Generated by Django 2.2.2 on 2019-06-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190621_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='content',
            field=models.TextField(max_length=8000),
        ),
    ]
